/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 15-июль-2025 17:32:02 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `comment` CASCADE
;

DROP TABLE IF EXISTS `m2m_tag_post` CASCADE
;

DROP TABLE IF EXISTS `post` CASCADE
;

DROP TABLE IF EXISTS `tag` CASCADE
;

DROP TABLE IF EXISTS `user` CASCADE
;

/* Create Tables */

CREATE TABLE `comment`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`content` VARCHAR(1024) NULL,
	`author_id` BIGINT NOT NULL,
	`post_id` BIGINT NOT NULL,
	CONSTRAINT `PK_comment` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `m2m_tag_post`
(
	`tag_id` INT NULL,
	`post_id` BIGINT NULL
)

;

CREATE TABLE `post`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(64) NOT NULL,
	`content` VARCHAR(1024) NOT NULL,
	`publication_date` DATETIME NOT NULL,
	`author_id` BIGINT NULL,
	CONSTRAINT `PK_post` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `tag`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(32) NULL,
	CONSTRAINT `PK_tag` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `user`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(32) NULL,
	`password_hash` VARCHAR(64) NOT NULL,
	`password_salt` VARCHAR(64) NOT NULL,
	`role` SMALLINT NOT NULL,
	`image_path` VARCHAR(255) NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `comment` 
 ADD INDEX `IXFK_comment_post` (`post_id` ASC)
;

ALTER TABLE `comment` 
 ADD INDEX `IXFK_comment_user` (`author_id` ASC)
;

ALTER TABLE `m2m_tag_post` 
 ADD INDEX `IXFK_m2m_tag_post_post` (`post_id` ASC)
;

ALTER TABLE `m2m_tag_post` 
 ADD INDEX `IXFK_m2m_tag_post_tag` (`tag_id` ASC)
;

ALTER TABLE `post` 
 ADD INDEX `IXFK_post_user` (`author_id` ASC)
;

ALTER TABLE `user` 
 ADD CONSTRAINT `UNQ_user_name` UNIQUE (`name` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `comment` 
 ADD CONSTRAINT `FK_comment_post`
	FOREIGN KEY (`post_id`) REFERENCES `post` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `comment` 
 ADD CONSTRAINT `FK_comment_user`
	FOREIGN KEY (`author_id`) REFERENCES `user` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `m2m_tag_post` 
 ADD CONSTRAINT `FK_m2m_tag_post_post`
	FOREIGN KEY (`post_id`) REFERENCES `post` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `m2m_tag_post` 
 ADD CONSTRAINT `FK_m2m_tag_post_tag`
	FOREIGN KEY (`tag_id`) REFERENCES `tag` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `post` 
 ADD CONSTRAINT `FK_post_user`
	FOREIGN KEY (`author_id`) REFERENCES `user` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
